## Trabalho 0

Criar um “hello world” para IPython+Numpy com os seguintes passos:


Criar uma matriz de inteiros  $\left\{0,1\right\}$, aleatória, $A$ de dimensão $1024\times 1024$ armazenada de forma compacta; usar Numpy.

## Constantes
    N - Número de linhas, colunas e incógnitas.
    A - Matriz aleatória gerada por 0 e 1 (apartir do metodo randint). 



In [98]:
import numpy as np

N = 10 #1024
A = np.random.randint(2,size = (N,N),dtype = np.uint8)
print(A.itemsize)
print(A)


1
[[0 0 0 0 1 1 1 1 0 1]
 [1 1 1 1 0 0 1 0 0 1]
 [0 1 0 0 0 1 0 1 0 1]
 [1 1 0 1 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0]
 [0 1 1 1 0 0 0 0 1 1]
 [0 1 0 1 0 0 1 0 1 1]
 [1 1 0 1 1 1 1 0 1 1]
 [1 0 1 1 1 0 0 1 1 0]
 [0 0 0 0 0 1 1 1 0 0]]


Explorar serializar/deserializar  $A$ usando pickle e JSON.

### Pickle:
    f - ficheiro que usamos para guardar a matriz comprimida
    B - Matriz usada para verificar se a matriz A foi guardada com sucesso
    
    

In [99]:
import pickle as pk

f = open('Matriz.txt','wb')


pk.dump(A,f)


f.close()

f = open('Matriz.txt','rb')

B = pk.load(f)

f.close()

print(np.array_equal(A,B))

True


### JSON:
    f - ficheiro que usamos para guardar a matriz comprimida
    C - Matriz usada para verificar se a matriz A foi guardada com sucesso
    

In [100]:
import json

f = open('MatrizJSON.txt','w')

json.dump(A.tolist(),f)

f.close()

f = open('MatrizJSON.txt','r')

C = np.array(json.load(f))

f.close()

print(np.array_equal(A,C))

True


Criar um “hello world” para Numberjack e um optimization-solver  (SCIP, Mistral, etc) formalizando e resolvendo o problema de encontrar um vector $x$ de $1024$ componentes inteiras $0,1$ de maior peso $|x| = \sum_i\,x_i$ que verifica as restrições
  1. Para todo $j$  tem-se $\sum_i\,A_{i,j}\,x_i = 1$ 
  2. Para todo $i$  tem-se $\sum_j\,A_{i,j}\,y_j = 1$

Formula matemática do modelo usado para o problema:
<br>
$\forall_{j\leq N}.\big(\sum_{i\leq N} A_{i,j}*x_{i}\big) \wedge
\forall_{i\leq N}.\big(\sum_{j\leq N} A_{i,j}*x_{j}\big) $

### Legenda:
    SC - Variável temporária igual à soma de uma coluna.
    SL - Variável temporária igual à soma de uma linha.
    model - Modelo usado para o problema.

In [101]:
from Numberjack import *

x = VarArray(N)
model = Model()
model.add(Maximise(sum(x)))


for j in range(N):
    SC = 0
    for i in range(N):
        SC += A[i][j]*x[i]
    model.add(SC==1)
    
for i in range(N):
    SL = 0
    for j in range(N):
        SL += A[i][j]*x[j]
    model.add(SL==1)

if model.load('SCIP').solve():
    for i in range(N):
        print(x[i].get_value(), end = ', ')
else:
    print('Não tem Solução')


Não tem Solução
